- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENCE.md
- README.md
First part of completing monorepo with essentials
> 11 standard for public code compliancy

- .npmrc
- apps/cms/config/server.ts
- apps/cms/dockerfile.dev
- apps/docs/dockerfile.dev
- apps/docs/docs/getting-started/development.md
- apps/nginx/development.conf
- apps/nginx/dockerfile.dev
- apps/web/dockerfile.dev
- docker-compose.dev.yml
- package.json
- pnpm-lock.yaml
After #63 the docker containers no longer work. This pr fixes the development containers. #66 Fixes containers for production.
> Development docker fix

- apps/cms/config/server.ts
- apps/cms/dockerfile.dev
- apps/docs/dockerfile.dev
- apps/web/dockerfile.dev
- docker-compose.dev.yml
- docker-compose.prod.yml
Another day another Docker fix. This PR fixes issues experienced on Ubuntu machines
> fix: docker for dev

- .github/ISSUE_TEMPLATE/work_package.md
Added template for work packages
> Update issue templates

- apps/web/src/pages/methoden.tsx
Heb WIP comment op beide cms pagina's gezet. Hierbij dezelfde tekst op de Methoden pagina.
> added wip comment on top

- .github/actions/build-and-push-docker/action.yml
- apps/docs/Dockerfile
- docker-compose.yml
Closes #128, Closes #134 (Merged due to touching the same areas)
> chore: fix docs hot reload in local develpoment / fix #134

- .gitignore
- apps/cms/src/api/publisher/content-types/publisher/schema.json
- apps/cms/src/api/publisher/controllers/publisher.ts
- apps/cms/src/api/publisher/routes/publisher.ts
- apps/cms/src/api/publisher/services/publisher.ts
- apps/web/package.json
- apps/web/src/helpers/strapi-database.ts
- apps/web/src/pages/api/publications/publish.ts
- yarn.lock
This pr creates and Next API endpoint that allows authorized users to request it. Upon a valid request the server will sync the releases locally with the supplied GitHub repo.
> Sync publications endpoint 

- .github/actions/publish-respec-document-release/action.yml
The publication action to be used by vendors who want to publish their ReSpec documents on regels.overheid.nl
> Publication action

- .github/workflows/semantic-release.yml
- apps/cms/src/api/application-metadata/content-types/application-metadata/schema.json
- apps/cms/src/api/application-metadata/controllers/application-metadata.ts
- apps/cms/src/api/application-metadata/routes/application-metadata.ts
- apps/cms/src/api/application-metadata/services/application-metadata.ts
- apps/web/src/app/api/publications/route.ts
- apps/web/src/components/application-metadata-provider.tsx
- apps/web/src/components/footer.tsx
- apps/web/src/pages/_app.tsx
- apps/web/src/services/cms/get-application-metadata.ts
- apps/web/src/stories/footer.stories.tsx
- apps/web/src/stories/notifications.stories.tsx
- apps/web/src/theme/components/mui-alert.tsx
- package.json
- yarn.lock
> Version number in footer

- apps/cms/src/api/page/content-types/page/schema.json
- apps/web/src/components/method-card.tsx
- apps/web/src/components/navbar.tsx
- apps/web/src/components/navbar/navbar-desktop.tsx
- apps/web/src/components/navbar/navbar-mobile.tsx
- apps/web/src/pages/404.tsx
- apps/web/src/pages/index.tsx
- apps/web/src/services/cms/get-page-by-slug.ts
- apps/web/src/services/cms/get-pages.ts
> Ordering navbar items

- CODE_OF_CONDUCT.md
Adopted from [design-system](https://github.com/MinBZK/design-system/blob/develop/CODE_OF_CONDUCT.md)
> Docs: Fix incomplete enforcement section

- apps/web/public/security.txt
> Add security.txt

- apps/cms/src/helpers/seed-metadata.ts
- apps/cms/src/helpers/seed-methods.ts
- apps/cms/src/helpers/seed-pages.ts
- apps/cms/src/helpers/seed-permissions.ts
- apps/cms/src/index.ts
- Added to the navbar methoden and roadmap
- Removed from the navbar particiepatiewet
- Added seed for application metadata
- Added seed for methoden
- Updated seed for permissions
note: this will only fix brand new dev environments existing ones will have to delete containers/volumes/databases
resolves: #234
> Update database seed

- apps/web/src/components/404-message/404-message-desktop.tsx
- apps/web/src/components/404-message/404-message-mobile.tsx
This pr updates the text in the 404 page and add a padding-bottom
> 404 Page spacing and text

- .github/workflows/semantic-release.yml
For real this time 😬
Forgot to commit the actual workflow in #245
> Changeset CI #2

- .changeset/rotten-suns-drive.md
- apps/docs/docs/getting-started/04-contributing.md
- apps/docs/docs/intro.md
Updated the docs to inform about the move away from semantic release in favour of changesets
> Documentation update

- .changeset/swift-insects-stare.md
- apps/web/next.config.js
- apps/web/src/app/methoden/page.tsx
- apps/web/src/app/publicaties/[...slug]/route.ts
- apps/web/src/app/publicaties/page.tsx
- apps/web/src/components/card/publication-card.tsx
Fixes the publication page showing 404
> Fix publications after build

- .changeset/chilly-crabs-sip.md
- apps/web/package.json
- apps/web/src/app/page.tsx
> Fix md tables not rendering

- .github/actions/build-and-release-respec-document/action.yml
- .github/actions/publish-respec-document-release/action.yml
No changeset needed as its doesn't modify any apps, will solve the issue with the images in the respec documents
> Upgrade actions

- .changeset/clever-poets-retire.md
- apps/web/src/app/layout.tsx
- apps/web/src/app/methoden/method-cards.tsx
- apps/web/src/app/methoden/page.tsx
- apps/web/src/app/not-found.tsx
- apps/web/src/app/page.tsx
- apps/web/src/app/publicaties/page.tsx
- apps/web/src/app/roadmap/page.tsx
- apps/web/src/components/container.tsx
- apps/web/src/components/footer.tsx
- apps/web/src/components/navbar.tsx
- apps/web/tailwind.config.js
> Implement content width

- .changeset/odd-rice-promise.md
- apps/docs/docs/getting-started/04-contributing.md
- apps/docs/docusaurus.config.js
> Edit this page redirecting to develop branch

- .changeset/late-schools-smile.md
- .changeset/nasty-swans-know.md
- .changeset/purple-shirts-hunt.md
- apps/web/src/app/publicaties/page.tsx
- apps/web/src/components/card/index.tsx
- apps/web/src/components/card/publication-card.tsx
- apps/web/src/components/common-override-able-component.tsx
> Work in progress publication variant

- .changeset/famous-chicken-drive.md
- apps/web/src/components/card/roadmap-quarter-cards-items.tsx
- apps/web/src/components/link.tsx
- apps/web/src/stories/components/link.stories.tsx
resolves #312 
- Link component can be seen [here](https://minbzk.github.io/regels.overheid.nl/pr-preview/pr-330/?path=/docs/components-link--docs) 
- Roadmap can be seen [here](https://minbzk.github.io/regels.overheid.nl/pr-preview/pr-330/?path=/story/pages-roadmap--default)
> Create link component with appropriate styles 

- .changeset/early-apes-hunt.md
- apps/web/.gitignore
- apps/web/src/app/media/cms/[file]/route.ts
- apps/web/src/common/resolve-from-public-public-dir.ts
> On demand image generation

- .changeset/cool-mangos-thank.md
- .changeset/early-apes-hunt.md
- .changeset/old-kids-warn.md
- .changeset/quiet-swans-sip.md
- apps/cms/src/api/blog-article/content-types/blog-article/schema.json
- apps/web/.gitignore
- apps/web/next.config.js
- apps/web/prisma/schema.prisma
- apps/web/src/app/(blog-article)/blog/[...slug]/page.tsx
- apps/web/src/app/(blog-article)/blog/[...slug]/share-bar.tsx
- apps/web/src/app/(common-page)/blog/article-card.tsx
- apps/web/src/app/media/cms/[file]/route.ts
- apps/web/src/app/navbar.tsx
- apps/web/src/common/resolve-cms-image.ts
- apps/web/src/common/resolve-from-public-public-dir.ts
- apps/web/src/common/truncate-string-at-word.ts
- apps/web/src/prisma/prisma-client.ts
- docker-compose.yml
resolves #358 
depends on #356 to be merged first
> Blog article sharing

- .changeset/clever-humans-pump.md
- .changeset/flat-dolphins-speak.md
- .changeset/fluffy-carrots-serve.md
- .changeset/fluffy-plums-smile.md
- .changeset/giant-ligers-pay.md
- .changeset/happy-masks-cheer.md
- .changeset/hip-wasps-pull.md
- .changeset/neat-countries-float.md
- .changeset/new-lemons-happen.md
- .changeset/poor-flowers-joke.md
- .changeset/sharp-points-exist.md
- .changeset/short-spoons-try.md
- .changeset/sour-files-vanish.md
- apps/web/src/app/(common-page)/blog/article-card.tsx
- apps/web/src/app/(common-page)/blog/page.tsx
- apps/web/src/app/(common-page)/methoden/method-card.tsx
- apps/web/src/app/(common-page)/methoden/methods-page.tsx
- apps/web/src/app/(common-page)/methoden/page.tsx
- apps/web/src/app/(common-page)/publicaties/page.tsx
- apps/web/src/app/(common-page)/publicaties/publication-card.tsx
- apps/web/src/app/(common-page)/roadmap/page.tsx
- apps/web/src/app/footer.tsx
- apps/web/src/app/navbar.tsx
- apps/web/src/common/resolve-cms-image.ts
- apps/web/src/components/card.tsx
- apps/web/src/components/container.tsx
- apps/web/src/components/pill.tsx
- apps/web/src/components/remote-mdx.tsx
> Batch fixes

- .changeset/nice-items-remain.md
- apps/docs/docs/ReSpec publicaties.md
publish.yml was missing config parameters
> Fix respec doc

- .changeset/twenty-rocked-pump.md
- apps/cms/src/api/page/content-types/page/schema.json
Adds an option to the cms Page model that marks pages as hidden from the navbar or not
> Option to hide pages from navbar

- .changeset/fluffy-laws-unite.md
- .changeset/orange-cats-bake.md
- apps/web/package.json
- apps/web/src/app/navbar.tsx
- pnpm-lock.yaml
Two known issues have been fix on the blog article page
1. #464 
2. Blog articles containing tables crashing the page, this happened after an upgrade to the `react-gfm` package
> Fix blog article page

- .changeset/soft-apples-peel.md
Changeset for the `web` environment was missing in #479
> Add web changeset

- .changeset/many-masks-move.md
- .github/configs/production/web/values.yml
- apps/web/src/app/(common-page)/publicaties/[...slug]/route.ts
> Add missing security headers

- .changeset/rude-coins-agree.md
- apps/web/src/app/(common-page)/lab/lab-item-card.tsx
- apps/web/src/components/method-navigation.tsx
Direct link is done trough the `method-navigation` component
resolves: #437
> Add direct link to demo from lab-item-card

- .changeset/selfish-trainers-roll.md
- apps/docs/docs/intro.md
> Document SBOM

- .changeset/chilly-rats-nail.md
- .changeset/rare-donuts-grin.md
- apps/web/src/app/menu-desktop.module.scss
- apps/web/src/app/menu-desktop.tsx
> Fixed desktop navigation submenu bugs

- .changeset/angry-rabbits-vanish.md
- apps/web/src/app/footer.tsx
> Fix footer layout

- .changeset/rare-ways-greet.md
- .changeset/tender-fans-fail.md
- apps/register/CPSV-AP-RONL/Custom_Namespace/ronl.ttl
- apps/register/CPSV-AP-RONL/Zorgtoeslag/zorgtoeslag-CPSV-AP-RONL.ttl
> validated ronl namespace
